blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/omar-dulaimi/json-to-prisma-schema-convertor/discussions/new
    about: Ask questions and discuss with others